name: build-freedom
on:
  push:
    paths:
    - 'freedom/**'
    - 'imgui/**'
    - 'include/**'
  workflow_dispatch:
    paths:
      - 'freedom/**'
      - 'imgui/**'
      - 'include/**'

jobs:
  windows-msvc:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Ciremun/gha-setup-vsdevenv@avoid-deprecation-warnings
        with:
          arch: 'x86'
      - name: build
        shell: cmd
        run: |
          build.bat
      - name: freedom
        uses: actions/upload-artifact@v3
        with:
          name: freedom
          path: |
            freedom.exe
            freedom.dll
            prejit.dll
